### ISSUE TITLE
Unit 8: User 'bob' can not use 'su-l' and 'sudo' commands

### ISSUE THREAD

**Issue by tscherf** [freeipa/freeipa-workshop#20]
When the hbac rule 'allow_all' is disabled, the user 'bob' can not use the   'su-l' and 'sudo' commands. It does work though for user 'alice' because she is a member of the 'sysadmin' group and has access to all commands through 'sysadmin_webservers' hbac rule.

Fix:
```
$ ipa hbacrule-add-service webadmin_webservers --hbacsvcs sudo --hbacsvcs su-l
```

**Comment by frasertweedale** [comment]
Fixed by https://github.com/freeipa/freeipa-workshop/pull/21.
