### ISSUE TITLE
Applying hbac rules according to guide doesn't return expected results

### ISSUE THREAD

**Issue by miskopo** [freeipa/freeipa-workshop#22]
## Description of problem:

I followed freeipa-guide closely up to unit 4 - hbac rules. 
After I created "sysadmin_webservers" using provided instructions (copy-pasted to be sure) I wanted to test, whether it works. 
However, despite Alice being in "sysadmin" group and all rules are set according to the guide, access to client servers for alice is denied (see Additional info)

## How reproducible:

Steps to Reproduce:
1. Follow the freeIPA-guide till Unit 4
2. Disable  allow_all hbac rule
3. Follow the steps in Unit 4

## Actual results:

 ```
 [server]$ ipa hbactest --host client.ipademo.local --service sshd --user alice
 ---------------------
 Access granted: False
 ---------------------
   Not matched rules: sysadmin_webservers
 ```
 ```
 [server]$ kinit alice
 Password for alice@IPADEMO.LOCAL:
 [server]$ ssh alice@client.ipademo.local
 Connection closed by UNKNOWN port 65535
 ```
## Expected results:
 ```
 [server]$ ipa hbactest --host client.ipademo.local --service sshd --user alice
 ---------------------
 Access granted: True
 ---------------------
 ```
 ```
 [server]$ kinit alice
 Password for alice@IPADEMO.LOCAL:
 [server]$ ssh alice@client.ipademo.local
 Creating home directory for alice.
 [alice@client]$
 ```
## Additional info:
 ```
 [server]$ ipa user-show alice
   User login: alice
   First name: Alice
   Last name: von der Wunderland
   Home directory: /home/alice
   Login shell: /bin/sh
   Principal name: alice@IPADEMO.LOCAL
   Principal alias: alice@IPADEMO.LOCAL
   Email address: alice@ipademo.local
   UID: 55400001
   GID: 55400001
   Job Title: Recreationist
   Class: Superior
   Account disabled: False
   Password: True
   Member of groups: sysadmin, ipausers
   Indirect Member of HBAC rule: sysadmin_webservers
   Kerberos keys available: True
```
```
 [server]$ ipa hbacrule-find
 -------------------
 1 HBAC rule matched
 -------------------
   Rule name: sysadmin_webservers
   Service category: all
   Enabled: TRUE
 ----------------------------
 Number of entries returned 1
 ----------------------------
```
```
 [server]$ ipa hbacrule-show sysadmin_webservers
   Rule name: sysadmin_webservers
   Service category: all
   Enabled: TRUE
   User Groups: sysadmin
   Host Groups: webservers
```

```
 [server]$ ipa --version
 VERSION: 4.6.90.pre2, API_VERSION: 2.229
```

**Comment by abbra** [comment]
Can you please explain what is `client.ipademo.local`? What OS does it run? Do you have output in /var/log/messages or journalctl around the time of failing ssh login?

**Comment by tscherf** [comment]
Did you complete this step:

> Instead of defining the HBAC rule to directly talk about client.ipademo.local, create a Host Group named webservers and add client.ipademo.local to it. You can do this via the Web UI or the ipa CLI program (don't forget to kinit admin; see if you can work out what plugin provides the host group functionality).

We did not give exact instructions in the manual how to do this because you should think about what is the correct process. So, please make sure the host 'client.ipademo.local' is a member of a host group called 'webservers'.

**Comment by miskopo** [comment]
adding `client.ipademo.local` to `webservers` using `ipa hostgroup-add-member` resolved the issue
