### ISSUE TITLE
service not running on https://server.ipademo.local/ ?

### ISSUE THREAD

**Issue by shapr** [freeipa/freeipa-workshop#26]
I gone through part of this workshop with the vagrant images. Section 3 asks the user to use the WebUI to add a user, but I was unable to find an open port 443. I tried using netcat to directly contact server.ipademo.local:443 but there's no service on that port.

Port forwarding in the vagrantfile looked fine to my non-expert understanding.

Is this something I should be able to easily work around?

**Comment by therealeldaria** [comment]
Did you do the steps mentioned in the first page?
Specifically:
Add entries for the guest VMs to your hosts file (so you can access them by their hostname)

**Comment by shapr** [comment]
Yes, I added entries for the guest VMs to my /etc/hosts file, and I am able to reach the http port 80 just fine.

**Comment by tscherf** [comment]
Can you share some more details about your setup? E.g., what is your host OS and do you use libvirt or Virtualbox?

> I gone through part of this workshop with the vagrant images. Section 3 asks the user to use the WebUI to add a user, but I was unable to find an open port 443. I tried using netcat to directly contact server.ipademo.local:443 but there's no service on that port.

So you are saying you can successfully ssh into server.ipademo.local and it's only the WebUI that doesn't work? Do you see the httpd service running when you connect directly to the box?

**Comment by shapr** [comment]
After checking /etc/hosts the IP address was off by ten, sorry for the noise!
